const products=[
{id:1,name:'Cyberpunk 2077',platform:'Steam',price:899,old:1299,icon:'🌃',genre:'RPG',region:'Global',desc:'Футуристическая RPG с открытым миром Night City.'},
{id:2,name:'Elden Ring',platform:'Steam',price:2499,old:3499,icon:'⚔️',genre:'Action RPG',region:'Global',desc:'Исследуй огромный мир и сражайся с опасными противниками.'},
{id:3,name:'EA SPORTS FC 26',platform:'EA',price:3199,old:3999,icon:'⚽',genre:'Sport',region:'EU',desc:'Футбольный симулятор EA SPORTS.'},
{id:4,name:"Assassin's Creed Shadows",platform:'Ubisoft',price:2299,old:2999,icon:'🥷',genre:'Action',region:'Global',desc:'Приключение в феодальной Японии.'},
{id:5,name:'Baldur’s Gate 3',platform:'Steam',price:2699,old:3499,icon:'🐉',genre:'RPG',region:'Global',desc:'Большая RPG с решениями, которые меняют историю.'},
{id:6,name:'The Sims 4',platform:'EA',price:799,old:999,icon:'🏠',genre:'Simulation',region:'Global',desc:'Создавай персонажей, дома и целые истории.'},
{id:7,name:'Rainbow Six Siege',platform:'Ubisoft',price:999,old:1499,icon:'🎯',genre:'Shooter',region:'Global',desc:'Тактический командный шутер.'},
{id:8,name:'Hogwarts Legacy',platform:'Steam',price:1799,old:2499,icon:'🪄',genre:'Adventure',region:'Global',desc:'Исследуй школу магии и окружающий мир.'}
];
let cart=JSON.parse(localStorage.getItem('kf_cart')||'[]'), filter='all', query='';
const money=n=>n.toLocaleString('ru-RU')+' ₽';
function save(){localStorage.setItem('kf_cart',JSON.stringify(cart));document.getElementById('cartCount').textContent=cart.length}
function toast(t){document.getElementById('toast').textContent=t;setTimeout(()=>document.getElementById('toast').textContent='',2200)}
function card(p){return `<article class="card"><a href="#/product/${p.id}"><div class="cover">${p.icon}</div></a><div class="card-body"><span class="tag">${p.platform} · ${p.region}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="row"><strong>${money(p.price)}</strong><button class="smallbtn" onclick="add(${p.id});event.preventDefault()">В корзину</button></div></div></article>`}
function home(){return `<section class="wrap hero"><div><div class="eyebrow">KeyForge</div><h1>Игры дешевле.<br><span>Покупка проще.</span></h1><p class="muted">Каталог цифровых игр, понятные цены и удобная покупка в одном месте.</p><a class="btn" href="#/catalog">Открыть каталог</a> <a class="btn alt" href="#/deals">Скидки</a></div><div class="showcase"><div class="bigcover">🎮</div><h2>Игра недели</h2><p class="muted">Cyberpunk 2077 · Steam · Global</p><div class="row"><span class="price">899 ₽</span><a class="smallbtn" href="#/product/1">Подробнее</a></div></div></section><section class="wrap"><div class="section-title"><div><span class="eyebrow">Популярное</span><h2>Лучшие предложения</h2></div><a href="#/catalog">Все игры →</a></div><div class="cards">${products.slice(0,4).map(card).join('')}</div></section><section class="wrap"><div class="banner"><span class="eyebrow">Почему KeyForge?</span><h2>Без лишнего усложнения</h2><p class="muted">Поиск → карточка игры → корзина → оплата → получение цифрового товара. В боевой версии сюда подключается реальный платёжный провайдер и лицензированный источник ключей.</p></div></section>`}
function catalog(){let list=products.filter(p=>(filter==='all'||p.platform===filter)&&p.name.toLowerCase().includes(query.toLowerCase()));return `<section class="wrap"><div class="section-title"><div><span class="eyebrow">Каталог</span><h2>Все игры</h2></div></div><div class="toolbar"><input placeholder="🔍 Поиск игры..." value="${query}" oninput="query=this.value;render()"><div class="chips"><button class="chip ${filter==='all'?'active':''}" onclick="filter='all';render()">Все</button><button class="chip ${filter==='Steam'?'active':''}" onclick="filter='Steam';render()">Steam</button><button class="chip ${filter==='EA'?'active':''}" onclick="filter='EA';render()">EA</button><button class="chip ${filter==='Ubisoft'?'active':''}" onclick="filter='Ubisoft';render()">Ubisoft</button></div></div><div class="cards">${list.length?list.map(card).join(''):'<div class="empty" style="grid-column:1/-1">Ничего не найдено</div>'}</div></section>`}
function product(id){let p=products.find(x=>x.id==id);if(!p)return notFound();return `<section class="wrap product-page"><div class="cover">${p.icon}</div><div class="panel"><span class="tag">${p.platform} · цифровой ключ</span><h1>${p.name}</h1><p class="muted">${p.desc}</p><div class="specs"><div class="spec"><small>Платформа</small>${p.platform}</div><div class="spec"><small>Регион</small>${p.region}</div><div class="spec"><small>Жанр</small>${p.genre}</div><div class="spec"><small>Выдача</small>После оплаты</div></div><div class="order"><div><div class="muted">Цена</div><div class="total">${money(p.price)}</div></div><button class="btn" onclick="add(${p.id})">Добавить в корзину</button></div><div class="notice" style="margin-top:15px">⚠️ Перед реальными продажами обязательно указывай точный регион активации и используй только ключи, полученные законным способом.</div></div></section>`}
function cartPage(){if(!cart.length)return `<section class="wrap"><div class="empty"><h2>Корзина пуста</h2><p class="muted">Добавь игру из каталога.</p><a class="btn" href="#/catalog">Перейти в каталог</a></div></section>`;let total=cart.reduce((s,p)=>s+p.price,0);return `<section class="wrap"><div class="section-title"><div><span class="eyebrow">Покупка</span><h2>Корзина</h2></div></div><div class="checkout-grid"><div class="panel">${cart.map((p,i)=>`<div class="cartline"><div class="carticon">${p.icon}</div><div style="flex:1"><b>${p.name}</b><div class="muted">${p.platform} · ${p.region}</div></div><strong>${money(p.price)}</strong><button class="smallbtn" onclick="removeCart(${i})">×</button></div>`).join('')}</div><div class="panel"><h2>Итого</h2><div class="row"><span class="muted">${cart.length} товар(а)</span><span class="total">${money(total)}</span></div><a class="btn" style="width:100%;text-align:center" href="#/checkout">Перейти к оформлению</a><p class="muted">Демо-режим: реальная оплата ещё не подключена.</p></div></div></section>`}
function checkout(){let total=cart.reduce((s,p)=>s+p.price,0);return `<section class="wrap"><div class="section-title"><div><span class="eyebrow">Оформление</span><h2>Данные заказа</h2></div></div><div class="checkout-grid"><div class="panel"><div class="form"><label>Email<input id="email" type="email" placeholder="you@example.com"></label><label>Имя<input id="name" placeholder="Ваше имя"></label><div class="notice">💳 Здесь подключается реальный платёжный провайдер. Нельзя считать заказ оплаченным только по нажатию кнопки.</div><button class="btn" onclick="demoOrder()">Создать тестовый заказ</button></div></div><div class="panel"><h3>Ваш заказ</h3>${cart.map(p=>`<div class="row" style="margin:10px 0"><span>${p.name}</span><b>${money(p.price)}</b></div>`).join('')}<hr><div class="row"><b>Итого</b><span class="total">${money(total)}</span></div></div></div></section>`}
function account(){let orders=JSON.parse(localStorage.getItem('kf_orders')||'[]');return `<section class="wrap account"><aside class="side"><a href="#/account">👤 Профиль</a><a href="#/orders">📦 Заказы</a><a href="#/catalog">🎮 Каталог</a></aside><div><span class="eyebrow">Личный кабинет</span><h2>Мой KeyForge</h2><div class="panel"><h3>Добро пожаловать</h3><p class="muted">Здесь будут профиль, история заказов и полученные цифровые товары.</p><p>Заказов: <b>${orders.length}</b></p></div></div></section>`}
function orders(){let o=JSON.parse(localStorage.getItem('kf_orders')||'[]');return `<section class="wrap"><span class="eyebrow">Личный кабинет</span><h2>Мои заказы</h2>${o.length?o.map(x=>`<div class="panel" style="margin:12px 0"><div class="row"><b>Заказ ${x.id}</b><span>${x.date}</span></div><p>${x.items.join(', ')}</p><span class="tag">Тестовый заказ · ключи не выдавались</span></div>`).join(''):'<div class="empty">Заказов пока нет.</div>'}</section>`}
function support(){return `<section class="wrap"><div class="panel"><span class="eyebrow">Помощь</span><h1>Поддержка</h1><p class="muted">Опиши проблему с заказом. В рабочей версии форма отправляется в систему поддержки.</p><div class="form"><input placeholder="Email"><input placeholder="Номер заказа"><input placeholder="Тема"><textarea style="min-height:140px;background:#10131a;color:#fff;border:1px solid #292f3b;border-radius:11px;padding:12px" placeholder="Сообщение"></textarea><button class="btn" onclick="toast('Сообщение сохранено в демо-режиме')">Отправить</button></div></div></section>`}
function legal(title,text){return `<section class="wrap"><div class="panel"><span class="eyebrow">KeyForge</span><h1>${title}</h1><p class="muted">${text}</p><p class="muted">Это шаблон страницы. Перед запуском продаж текст оферты, возвратов, обработки данных и реквизиты необходимо адаптировать под страну регистрации бизнеса и фактическую модель магазина.</p></div></section>`}
function deals(){return `<section class="wrap"><span class="eyebrow">Выгодно</span><h2>Скидки</h2><div class="cards">${products.filter(p=>p.old>p.price).map(card).join('')}</div></section>`}
function notFound(){return `<section class="wrap"><div class="empty"><h2>Страница не найдена</h2><a class="btn" href="#/">На главную</a></div></section>`}
function add(id){let p=products.find(x=>x.id==id);cart.push(p);save();toast('Добавлено в корзину');}
function removeCart(i){cart.splice(i,1);save();render()}
function demoOrder(){if(!document.getElementById('email').value)return toast('Укажи email');let orders=JSON.parse(localStorage.getItem('kf_orders')||'[]');orders.push({id:'#KF'+Date.now().toString().slice(-6),date:new Date().toLocaleString('ru-RU'),items:cart.map(p=>p.name)});localStorage.setItem('kf_orders',JSON.stringify(orders));cart=[];save();location.hash='/orders';toast('Тестовый заказ создан')}
function openSearch(){let el=document.getElementById('searchModal');if(!el){el=document.createElement('div');el.id='searchModal';el.className='search-modal';el.innerHTML='<div class="search-box"><input autofocus placeholder="Поиск игры..." oninput="query=this.value;location.hash=\'/catalog\';document.getElementById(\'searchModal\').classList.remove(\'open\')"></div>';document.body.appendChild(el)}el.classList.add('open');el.onclick=e=>{if(e.target===el)el.classList.remove('open')}}
function render(){save();let path=location.hash.slice(1)||'/';let c=path==='/'?home():path==='/catalog'?catalog():path==='/cart'?cartPage():path==='/checkout'?checkout():path==='/account'?account():path==='/orders'?orders():path==='/support'?support():path==='/deals'?deals():path==='/terms'?legal('Условия покупки','Здесь размещаются правила продажи цифровых товаров, оплаты, доставки и возврата.'):path==='/privacy'?legal('Конфиденциальность','Здесь размещается политика обработки персональных данных.'):path.startsWith('/product/')?product(path.split('/')[2]):notFound();document.getElementById('app').innerHTML=c;window.scrollTo(0,0)}
window.addEventListener('hashchange',render);render();
